export const theme = Object.freeze({
  colors: {
    white: "#fff",
    skyblue: "#1f8ecd",
    brightBlue: "#1ea1f7",
    paleGray: "#eaeaea",
    silver: "#cdd2d2",
    offWhite: "#f2f2f2",
    lightestGray: "#ededed",
    lightGray: "#879292",
    darkGray: "#5e5e5e",
    emerald: "#2daf7f",
    golden: "#e19205",
    brightRed: "#ee5a52",
  },
  fonts: {
    fontFamily: "opgg",
  },
  spacing: {
    xs: "0.8rem",
    sm: "1rem",
    md: "1.2rem",
    lg: "1.4rem",
    xl: "1.6rem",
  },
  fontSizes: {
    xs: "1.1rem",
    sm: "1.2rem",
    md: "1.4rem",
    lg: "1.6rem",
    xl: "2rem",
    xxl: "2.4rem",
  },
  maxWidth: "108rem",
});
